image: ubuntu:14.04
stages:
  - build
  - test
  - release-job

cache:
  paths:
  - apt-cache/

before_script:
  - export APT_CACHE_DIR=`pwd`/apt-cache && mkdir -pv $APT_CACHE_DIR
  - debconf-set-selections <<< 'mysql-server mysql-server/root_password password root'
  - debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password root'
  - apt update && apt-get install -o dir::cache::archives="$APT_CACHE_DIR" -y mysql-server mono-complete monodevelop monodevelop-nunit git nunit nunit-console

build:
  stage: build
  script:
    - ./scripts/build.sh

release-job:
  script:
    - ./scripts/build.sh
  artifacts:
    paths:
      - .
  only:
    - devel
    - tags
